{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ashwork",
    "module": "functionality",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.ashwork",
          "module": "callability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "functionality-1.0.0.jar",
          "url": "functionality-1.0.0.jar",
          "size": 374,
          "sha512": "0b03ebd7fd5d07a314d472315d66b8abd0501fa4443d9f65d03a0b2001bb65416afc43a0efdd61af24bc524e3a3284ddb37311191c15a8a02568aba82fb12d3f",
          "sha256": "d63b8239905fb35aeb16d2dff3a3ecf58ae35b0528aa5dafab2508dbc8e82877",
          "sha1": "65d5e77bee599a6fcadaefb301d3a6743077efa1",
          "md5": "7f7dfb3bda3fc690ad5853030faff2a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.ashwork",
          "module": "callability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "functionality-1.0.0.jar",
          "url": "functionality-1.0.0.jar",
          "size": 374,
          "sha512": "0b03ebd7fd5d07a314d472315d66b8abd0501fa4443d9f65d03a0b2001bb65416afc43a0efdd61af24bc524e3a3284ddb37311191c15a8a02568aba82fb12d3f",
          "sha256": "d63b8239905fb35aeb16d2dff3a3ecf58ae35b0528aa5dafab2508dbc8e82877",
          "sha1": "65d5e77bee599a6fcadaefb301d3a6743077efa1",
          "md5": "7f7dfb3bda3fc690ad5853030faff2a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "functionality-1.0.0-sources.jar",
          "url": "functionality-1.0.0-sources.jar",
          "size": 261,
          "sha512": "65e32baff2298e992bd882f0884cce68b63d1eead719fb7801acabfb45e46316d6d63bfc7f49032860078716dfc4cec4a225caf311dac416da7bf3028ac3d59c",
          "sha256": "839e4e9743675c3136f95ad3f7f9fd452772fd46824b16d39a546590281726f8",
          "sha1": "7600d0684864a7cd95718cfcc2c820046e2535af",
          "md5": "42b04524229916d33d78660ba2e58925"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "functionality-1.0.0-javadoc.jar",
          "url": "functionality-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "65e32baff2298e992bd882f0884cce68b63d1eead719fb7801acabfb45e46316d6d63bfc7f49032860078716dfc4cec4a225caf311dac416da7bf3028ac3d59c",
          "sha256": "839e4e9743675c3136f95ad3f7f9fd452772fd46824b16d39a546590281726f8",
          "sha1": "7600d0684864a7cd95718cfcc2c820046e2535af",
          "md5": "42b04524229916d33d78660ba2e58925"
        }
      ]
    }
  ]
}
