{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ashwork",
    "module": "codecable",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "net.ashwork",
          "module": "callability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "codecable-1.0.0.jar",
          "url": "codecable-1.0.0.jar",
          "size": 13927,
          "sha512": "3ae41c4e6b87cce86afcb8428f37edd52dc02672067c8335a89f2e5758702169ab95343289d0046ea1593249cf0ccc5c9ac92697af85c72816caec3ef07c1b5e",
          "sha256": "44220ea00bd1ae50b50538798b0eecd9b65aa931c56f5a5d407a43037ee0da5b",
          "sha1": "28dd7c234d87202f31afcabca811b22302b42bd7",
          "md5": "cec69b378f68a6d83bc9116dca84e99b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "net.ashwork",
          "module": "callability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "codecable-1.0.0.jar",
          "url": "codecable-1.0.0.jar",
          "size": 13927,
          "sha512": "3ae41c4e6b87cce86afcb8428f37edd52dc02672067c8335a89f2e5758702169ab95343289d0046ea1593249cf0ccc5c9ac92697af85c72816caec3ef07c1b5e",
          "sha256": "44220ea00bd1ae50b50538798b0eecd9b65aa931c56f5a5d407a43037ee0da5b",
          "sha1": "28dd7c234d87202f31afcabca811b22302b42bd7",
          "md5": "cec69b378f68a6d83bc9116dca84e99b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codecable-1.0.0-sources.jar",
          "url": "codecable-1.0.0-sources.jar",
          "size": 8267,
          "sha512": "d526820ed97a53fd556ad0760f48d3ad7e524dfc7350d8372e6b13e9155102f31f48fb8c91fc37252bd9c19fcd8d89d534d9caccc92875e7e9950299ccadcbc1",
          "sha256": "a6ae972c1799e9c7e6d00e279df01f640f0c320fa835384b98b7de4e502f446f",
          "sha1": "b071323973b0d3d00e9364d5478768c14528ea5f",
          "md5": "bc272c3cbd7fde19592d8e2033d39d44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codecable-1.0.0-javadoc.jar",
          "url": "codecable-1.0.0-javadoc.jar",
          "size": 133211,
          "sha512": "f624111d253042cd5d001655efada215631fb24880d23313cb4ddaf8b8697f43652df843429bf01b6fd7013464d40503f5926471408c7557257296eeb0503fa4",
          "sha256": "b2f4b0f6e68f0417b81da3cc97162099e529a8a0c66a35b74141657039a01ee0",
          "sha1": "695a6509b164ef92105035a1cdc0f9fce7ed2bdf",
          "md5": "d3ad71072a65698c89cc2b0a63fa917d"
        }
      ]
    }
  ]
}
