{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ashwork",
    "module": "functionality-all",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.ashwork",
          "module": "functionality",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "consumability",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "operating",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "predicating",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "throwability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "functionality-all-1.0.0.jar",
          "url": "functionality-all-1.0.0.jar",
          "size": 374,
          "sha512": "bab84f96a183c28872d7d62c8d68c5396f15835cdb8e2fd1abb3a24600619dfbe6b01dbac14053fc6582f7b1f51da233bca6de3a612f2a1d644f1a73d6658cb1",
          "sha256": "c20cd51f51bf70625afab91e532b8de73b9042f24b64701ca6e0b85747393c4b",
          "sha1": "6a87837e6327d99755039049c2428b91441b2d2c",
          "md5": "e4260d84f19dfe50e78cd8e9c2149856"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.ashwork",
          "module": "functionality",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "consumability",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "operating",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "predicating",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.ashwork",
          "module": "throwability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "functionality-all-1.0.0.jar",
          "url": "functionality-all-1.0.0.jar",
          "size": 374,
          "sha512": "bab84f96a183c28872d7d62c8d68c5396f15835cdb8e2fd1abb3a24600619dfbe6b01dbac14053fc6582f7b1f51da233bca6de3a612f2a1d644f1a73d6658cb1",
          "sha256": "c20cd51f51bf70625afab91e532b8de73b9042f24b64701ca6e0b85747393c4b",
          "sha1": "6a87837e6327d99755039049c2428b91441b2d2c",
          "md5": "e4260d84f19dfe50e78cd8e9c2149856"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "functionality-all-1.0.0-sources.jar",
          "url": "functionality-all-1.0.0-sources.jar",
          "size": 261,
          "sha512": "65e00cbac282350fc751b8760fab526a426402e4d88a659b01625cf19f9d37845d6ef62a5b81516e68b7849b60a2b2f77b956cf472e3952203f842eafb4b46e1",
          "sha256": "087944e9f9dd65c4e8d13b35f6d46e00a3a14db6a4b1086ab594c4431b7f6172",
          "sha1": "43f6e4da25888ec0c988660c4e3dacc25dcb1e9e",
          "md5": "3784cf309e550e5f71bf4239778406b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "functionality-all-1.0.0-javadoc.jar",
          "url": "functionality-all-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "65e00cbac282350fc751b8760fab526a426402e4d88a659b01625cf19f9d37845d6ef62a5b81516e68b7849b60a2b2f77b956cf472e3952203f842eafb4b46e1",
          "sha256": "087944e9f9dd65c4e8d13b35f6d46e00a3a14db6a4b1086ab594c4431b7f6172",
          "sha1": "43f6e4da25888ec0c988660c4e3dacc25dcb1e9e",
          "md5": "3784cf309e550e5f71bf4239778406b3"
        }
      ]
    }
  ]
}
