{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ashwork",
    "module": "codecable",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "net.ashwork",
          "module": "callability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "codecable-1.1.0.jar",
          "url": "codecable-1.1.0.jar",
          "size": 17195,
          "sha512": "717990f310789cfdba0bf166a0cacb9ef86d93f949bf21bcc9ac4d98780702005bd6ddf3bc0f51e153c811474487d832e30915dc9db4a47c80cd7f6d85f61508",
          "sha256": "2849e8c704d7ae93657a81807b267374d02c8106a72290a87062aa8b3e32c4a2",
          "sha1": "83a4dcb66e48280f35f20928d20be75f6fde5690",
          "md5": "35e37de28204c87cae1582a0e771a9da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "net.ashwork",
          "module": "callability",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "codecable-1.1.0.jar",
          "url": "codecable-1.1.0.jar",
          "size": 17195,
          "sha512": "717990f310789cfdba0bf166a0cacb9ef86d93f949bf21bcc9ac4d98780702005bd6ddf3bc0f51e153c811474487d832e30915dc9db4a47c80cd7f6d85f61508",
          "sha256": "2849e8c704d7ae93657a81807b267374d02c8106a72290a87062aa8b3e32c4a2",
          "sha1": "83a4dcb66e48280f35f20928d20be75f6fde5690",
          "md5": "35e37de28204c87cae1582a0e771a9da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codecable-1.1.0-sources.jar",
          "url": "codecable-1.1.0-sources.jar",
          "size": 9524,
          "sha512": "d34c02e68353b18560deec7878be6285a5f247732736d30474fe65e4c91e15c8643f8a5aab6b82ba4c528664b9b474c84b8a22291bb961ba3da1f111fbf22d6a",
          "sha256": "9cb43df20879c61650347c0eaa5aa3804362e3e0560c1c7d389c7f84a0b521d9",
          "sha1": "3959f5e6d78e66dff89917568dea9776bd9e28dc",
          "md5": "58a3e91529ce034646e96818754adab7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codecable-1.1.0-javadoc.jar",
          "url": "codecable-1.1.0-javadoc.jar",
          "size": 134725,
          "sha512": "58f1a63cab2e28324d528412db28f95dae2c83a0e6b33a802edf96f124bb2c256a4b50ecf12d7fae0a774455bb91fb6475b6243730a4048df4f808151baad0ea",
          "sha256": "6d788f217f72186110c721d46bc523b2529cfb89ef4179a915cdd7f49ff1443d",
          "sha1": "ed0d5b9ada3c24fdec8b06c11b41319b27f14916",
          "md5": "5a2f9c857ddbfc08dca30ce90f739076"
        }
      ]
    }
  ]
}
