{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ashwork",
    "module": "aritiality",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aritiality-1.0.0.jar",
          "url": "aritiality-1.0.0.jar",
          "size": 5639,
          "sha512": "a2b3928067e49b764d2a405229f68a79ac7f54410e6a25031a020c15fb0ad73e68eb9b45a381893815af0ad9540d9717ef166869c4bfc241641438bb3b139b99",
          "sha256": "b7a8772b68de7d65851e347bab4b6df8c5209c4557d475c42c4e97ed1f65f28f",
          "sha1": "09c5e20c13f200cd6119fcc54f7190a1390f3d59",
          "md5": "0c16df506946b0100edd1cae37f494b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aritiality-1.0.0.jar",
          "url": "aritiality-1.0.0.jar",
          "size": 5639,
          "sha512": "a2b3928067e49b764d2a405229f68a79ac7f54410e6a25031a020c15fb0ad73e68eb9b45a381893815af0ad9540d9717ef166869c4bfc241641438bb3b139b99",
          "sha256": "b7a8772b68de7d65851e347bab4b6df8c5209c4557d475c42c4e97ed1f65f28f",
          "sha1": "09c5e20c13f200cd6119fcc54f7190a1390f3d59",
          "md5": "0c16df506946b0100edd1cae37f494b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aritiality-1.0.0-sources.jar",
          "url": "aritiality-1.0.0-sources.jar",
          "size": 5817,
          "sha512": "dc5f1688ca1266e2c73f5ec1ca6dd35f7a22a56b57bf04393bf7b00bc465f11a589de912bcb1acb0882c99b7a247d235b6edc6376b4690c6e4b163d8fdbf7e23",
          "sha256": "6004ddffc5cdbff0b749ed8958de24771af40e82e748816e313580efc3eb5480",
          "sha1": "bdf552bf6d8e1f7f31640b3a08819b7c072c78f3",
          "md5": "b58eef7c5b483b36c7333644cb8a2bd9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aritiality-1.0.0-javadoc.jar",
          "url": "aritiality-1.0.0-javadoc.jar",
          "size": 42843,
          "sha512": "dab6a0a443621e66f4a248632735f44fd9b6f275f0e489e72f4bc817460f2513616ab8c99c46cd430e69841b161e809b32ad1ca419982eb6c51d8c4dbb322369",
          "sha256": "97cef5bc43c9dcf3f45d53174dcad1f6bc453eedbd1b2098a24e53dd253b553d",
          "sha1": "f350575e8051df2bdf2eadb5976a4ec2abaae0e8",
          "md5": "774b1d79bb0ffb94b26f16a8b1204cff"
        }
      ]
    }
  ]
}
