{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ashwork",
    "module": "callability",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callability-1.0.0.jar",
          "url": "callability-1.0.0.jar",
          "size": 3549,
          "sha512": "0b33450be9cf2fefd2b112800b39422548d2ff3f855ace0a2a83d8dfc72cc3a04ce4e62dffea2ff97375b7738c72af42eb5b714530c6aeea7ab6e09f13e33b5d",
          "sha256": "3ef3aa9d8ee5c3524a68b3948f67aff4b6165fdbf4b29dca4f5edc472c3e3fd9",
          "sha1": "5b6d9d6b9faaff59b6f96a80eaef5e331b96483e",
          "md5": "5bf81ecb8e846a800d1fb490d4afd78d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callability-1.0.0.jar",
          "url": "callability-1.0.0.jar",
          "size": 3549,
          "sha512": "0b33450be9cf2fefd2b112800b39422548d2ff3f855ace0a2a83d8dfc72cc3a04ce4e62dffea2ff97375b7738c72af42eb5b714530c6aeea7ab6e09f13e33b5d",
          "sha256": "3ef3aa9d8ee5c3524a68b3948f67aff4b6165fdbf4b29dca4f5edc472c3e3fd9",
          "sha1": "5b6d9d6b9faaff59b6f96a80eaef5e331b96483e",
          "md5": "5bf81ecb8e846a800d1fb490d4afd78d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callability-1.0.0-sources.jar",
          "url": "callability-1.0.0-sources.jar",
          "size": 3131,
          "sha512": "bd6e814ff11d9a4c14b353315fc567f002b4fea4e0b3374e3a7d06dd3da15a9d5c94df45e9e43b7dcf23682ad2858c9411b8adc5c3f58930061320dd2f62b1a7",
          "sha256": "2214472b2c9dbf3f1a67b18b3c0529afa6f76c037f415dd4f6f142ad77b9e36e",
          "sha1": "756d2ebfc03e22c5b36e8c208136355b30cfeeb4",
          "md5": "cde82ed8340004f9f802dfbd9f86a818"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callability-1.0.0-javadoc.jar",
          "url": "callability-1.0.0-javadoc.jar",
          "size": 23518,
          "sha512": "f05077a2872476de07a56525e5dbab55f1f52bd3784ece8e48e5faf5400aee1c442c0f5cbf640a72025b3cb6e1d0108626d2b2772c72eed82bbf42a1d8514e00",
          "sha256": "027c3eb1b4c8aa10a1c599bff3f6b4cab739dfeb92018ba95d214ad845eb7b34",
          "sha1": "17d846b1bf9661aabebd3489c1421b4ce92ecebb",
          "md5": "7c31290fb545c1583267f14feca3a027"
        }
      ]
    }
  ]
}
